### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by techniq** [techniq/github-analysis#2]
## Contributions
- [ ] Show individual commits (in list and/or as drilldown)
- [ ] Group day, repo
- [ ] Show issues
- [ ] Quick way to select range (DateRange) but still allow typing in dates
- [ ] Add link to repo
- [ ] Make repo public
